# Generated by Django 3.0.8 on 2020-07-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field', models.TextField(max_length=9999)),
                ('post_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
