# Generated by Django 3.0.8 on 2020-07-27 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_auto_20200726_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 27, 7, 21, 32, 938960, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
