# Generated by Django 3.0.8 on 2020-07-28 16:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_auto_20200728_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='like',
            name='liked_by',
        ),
        migrations.AddField(
            model_name='like',
            name='liked_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
